### ISSUE TITLE
GitHub Actions refactor

### ISSUE THREAD

**Issue by djjudas21** [liturgical-app/calendar-api#19]
Currently, there is a GitHub Actions workflow auto-creates a new release of the project when a PR is merged into `main`.

Personally, I would prefer that the process to create a release was manual. This would give the ability to bundle up multiple PRs into one release (e.g. [camerahub 0.37.1](https://github.com/camerahub/camerahub/releases/tag/0.37.1), and to choose the version number according to semver.

I would prefer that the various workflow files were standalone, didn't call other workflows as this makes it harder to debug, and each workflow file was standalone with its own `on:` trigger condition.

What do you think, @jrsmth? If you're happy, I'll crack on and make the changes

**Comment by jrsmth** [comment]
Yep happy for that; the `main` merge auto-release was designed so that the `develop` branch tracked the next feature (with the next release version).

But all in all, happy for changes to made on this
